version: "3.9"

services:
  ai:
    build: ./ai-service
    env_file: ./.env
    environment:
      - AI_MODE=${AI_MODE}
      - MODEL_PTH_PATH=${MODEL_PTH_PATH}
      - CLASS_MAP_PATH=${CLASS_MAP_PATH}
      - NUM_CLASSES=${NUM_CLASSES}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - CLIP_MODEL_NAME=${CLIP_MODEL_NAME}
      - INDEX_DIR=${INDEX_DIR}
      - TOPK=${TOPK}
    volumes:
      - ./ai-service/index:/app/index
      - ./ai-service/models:/app/models
    ports:
      - "${AI_PORT}:8000"

  spring:
    build: ./backend-spring
    env_file: ./.env
    environment:
      - AI_BASE_URL=${AI_BASE_URL}
      - SPRING_PORT=${SPRING_PORT}
    depends_on:
      - ai
    ports:
      - "${SPRING_PORT}:8080"

  nginx:
    build: ./nginx
    env_file: ./.env
    depends_on:
      - spring
      - ai
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
